// packages/next-app/src/components/AppBar.tsx
"use client";
import { useCartBloc } from "@/app/page";
import { usePlocState } from "@/common/usePlocState";

const AppBar: React.FC = () => {
    const ploc = useCartBloc();
    const state = usePlocState(ploc);

    const totalItems = state.kind === "UpdatedCartState" ? state.totalItems : 0;

    return (
        <div>
            <button onClick={() => ploc.openCart()}>Cart {totalItems}</button>
        </div>
    );
};

export default AppBar;

// packages/main/cart/src/presentation/components/AppBar.vue
<script setup lang="ts">
  import { inject } from 'vue';
  import { type CartPloc } from '@core/cart';
  import { usePlocState } from '@lib/vue-ploc';

  const cartBloc = inject<CartPloc>('cartBloc') as CartPloc;
  const state = usePlocState(cartBloc);

  const handleOpenCart = () => {
    cartBloc?.openCart();
  };
</script>

<template>
  <button @click="handleOpenCart">
    Cart {{ state.totalItems ? state.totalItems.toString() : '0' }}
  </button>
</template>
